# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 511, 281))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.parametersLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.parametersLayout.setContentsMargins(24, 0, 0, 0)
        self.parametersLayout.setSpacing(0)
        self.parametersLayout.setObjectName("parametersLayout")
        self.heartRateLayout = QtWidgets.QHBoxLayout()
        self.heartRateLayout.setSpacing(24)
        self.heartRateLayout.setObjectName("heartRateLayout")
        self.heart_rate_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.heart_rate_label.setMinimumSize(QtCore.QSize(82, 68))
        self.heart_rate_label.setObjectName("heart_rate_label")
        self.heartRateLayout.addWidget(self.heart_rate_label)
        self.heart_rate_slider = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heart_rate_slider.sizePolicy().hasHeightForWidth())
        self.heart_rate_slider.setSizePolicy(sizePolicy)
        self.heart_rate_slider.setMinimumSize(QtCore.QSize(180, 27))
        self.heart_rate_slider.setMaximumSize(QtCore.QSize(313, 27))
        self.heart_rate_slider.setMaximum(200)
        self.heart_rate_slider.setProperty("value", 100)
        self.heart_rate_slider.setOrientation(QtCore.Qt.Horizontal)
        self.heart_rate_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.heart_rate_slider.setTickInterval(10)
        self.heart_rate_slider.setObjectName("heart_rate_slider")
        self.heartRateLayout.addWidget(self.heart_rate_slider)
        self.heart_rate_value = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.heart_rate_value.setObjectName("heart_rate_value")
        self.heartRateLayout.addWidget(self.heart_rate_value)
        self.parametersLayout.addLayout(self.heartRateLayout)
        self.respiratoryRateLayout = QtWidgets.QHBoxLayout()
        self.respiratoryRateLayout.setSpacing(24)
        self.respiratoryRateLayout.setObjectName("respiratoryRateLayout")
        self.respiratory_rate_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.respiratory_rate_label.setMinimumSize(QtCore.QSize(82, 68))
        self.respiratory_rate_label.setObjectName("respiratory_rate_label")
        self.respiratoryRateLayout.addWidget(self.respiratory_rate_label)
        self.respiratory_rate_slider = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.respiratory_rate_slider.setMinimumSize(QtCore.QSize(152, 25))
        self.respiratory_rate_slider.setMaximumSize(QtCore.QSize(313, 27))
        self.respiratory_rate_slider.setMaximum(200)
        self.respiratory_rate_slider.setProperty("value", 100)
        self.respiratory_rate_slider.setOrientation(QtCore.Qt.Horizontal)
        self.respiratory_rate_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.respiratory_rate_slider.setTickInterval(10)
        self.respiratory_rate_slider.setObjectName("respiratory_rate_slider")
        self.respiratoryRateLayout.addWidget(self.respiratory_rate_slider)
        self.respiratory_rate_value = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.respiratory_rate_value.setObjectName("respiratory_rate_value")
        self.respiratoryRateLayout.addWidget(self.respiratory_rate_value)
        self.parametersLayout.addLayout(self.respiratoryRateLayout)
        self.bloodPressureLayout = QtWidgets.QHBoxLayout()
        self.bloodPressureLayout.setSpacing(24)
        self.bloodPressureLayout.setObjectName("bloodPressureLayout")
        self.blood_pressure_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.blood_pressure_label.setMinimumSize(QtCore.QSize(82, 67))
        self.blood_pressure_label.setObjectName("blood_pressure_label")
        self.bloodPressureLayout.addWidget(self.blood_pressure_label)
        self.blood_pressure_slider = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.blood_pressure_slider.setMinimumSize(QtCore.QSize(152, 25))
        self.blood_pressure_slider.setMaximumSize(QtCore.QSize(313, 27))
        self.blood_pressure_slider.setMaximum(200)
        self.blood_pressure_slider.setProperty("value", 100)
        self.blood_pressure_slider.setOrientation(QtCore.Qt.Horizontal)
        self.blood_pressure_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.blood_pressure_slider.setTickInterval(10)
        self.blood_pressure_slider.setObjectName("blood_pressure_slider")
        self.bloodPressureLayout.addWidget(self.blood_pressure_slider)
        self.blood_pressure_value = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.blood_pressure_value.setObjectName("blood_pressure_value")
        self.bloodPressureLayout.addWidget(self.blood_pressure_value)
        self.parametersLayout.addLayout(self.bloodPressureLayout)
        self.consciousLayout = QtWidgets.QHBoxLayout()
        self.consciousLayout.setSpacing(24)
        self.consciousLayout.setObjectName("consciousLayout")
        self.conscious_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.conscious_label.setObjectName("conscious_label")
        self.consciousLayout.addWidget(self.conscious_label)
        self.conscious_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.conscious_checkbox.setText("")
        self.conscious_checkbox.setObjectName("conscious_checkbox")
        self.consciousLayout.addWidget(self.conscious_checkbox)
        self.parametersLayout.addLayout(self.consciousLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.heart_rate_slider.valueChanged['int'].connect(self.heart_rate_value.setNum)
        self.respiratory_rate_slider.valueChanged['int'].connect(self.respiratory_rate_value.setNum)
        self.blood_pressure_slider.valueChanged['int'].connect(self.blood_pressure_value.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.heart_rate_slider, self.respiratory_rate_slider)
        MainWindow.setTabOrder(self.respiratory_rate_slider, self.blood_pressure_slider)
        MainWindow.setTabOrder(self.blood_pressure_slider, self.conscious_checkbox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.heart_rate_label.setText(_translate("MainWindow", "Heart Rate"))
        self.heart_rate_value.setText(_translate("MainWindow", "100"))
        self.respiratory_rate_label.setText(_translate("MainWindow", "Respiratory Rate"))
        self.respiratory_rate_value.setText(_translate("MainWindow", "100"))
        self.blood_pressure_label.setText(_translate("MainWindow", "Blood Pressure"))
        self.blood_pressure_value.setText(_translate("MainWindow", "100"))
        self.conscious_label.setText(_translate("MainWindow", "Conscious?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
